//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKMonitor.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MESWebserviceSoap")]
    public interface MESWebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MES_Bom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MES_Bom(string cpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MES_Bom_order", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MES_Bom_order(string orderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MES_MatrialsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MES_MatrialsList(string orderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MES_Matrials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MES_Matrials(string cpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MES_MatrialsVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MES_MatrialsVersion(string cpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MES_MatrialsVersion_order", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MES_MatrialsVersion_order(string orderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INV_Files", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable INV_Files(string matrialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MES_BomAndMaterials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MES_BomAndMaterials(string productNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MESWebserviceSoapChannel : HKMonitor.ServiceReference1.MESWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MESWebserviceSoapClient : System.ServiceModel.ClientBase<HKMonitor.ServiceReference1.MESWebserviceSoap>, HKMonitor.ServiceReference1.MESWebserviceSoap {
        
        public MESWebserviceSoapClient() {
        }
        
        public MESWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MESWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MESWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MESWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable MES_Bom(string cpCode) {
            return base.Channel.MES_Bom(cpCode);
        }
        
        public System.Data.DataTable MES_Bom_order(string orderNo) {
            return base.Channel.MES_Bom_order(orderNo);
        }
        
        public System.Data.DataTable MES_MatrialsList(string orderNo) {
            return base.Channel.MES_MatrialsList(orderNo);
        }
        
        public System.Data.DataTable MES_Matrials(string cpCode) {
            return base.Channel.MES_Matrials(cpCode);
        }
        
        public System.Data.DataTable MES_MatrialsVersion(string cpCode) {
            return base.Channel.MES_MatrialsVersion(cpCode);
        }
        
        public System.Data.DataTable MES_MatrialsVersion_order(string orderNo) {
            return base.Channel.MES_MatrialsVersion_order(orderNo);
        }
        
        public System.Data.DataTable INV_Files(string matrialNo) {
            return base.Channel.INV_Files(matrialNo);
        }
        
        public System.Data.DataSet MES_BomAndMaterials(string productNo) {
            return base.Channel.MES_BomAndMaterials(productNo);
        }
    }
}
